server:
  port: 8080


spring:
  application:
    name: sp25-hsf302-group3-se1889vj
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=hsf302;encrypt=true;trustServerCertificate=true
    username: sa
    password: 1409
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  mail:
    host: smtp.gmail.com
    port: 465
    protocol: smtps
    username: allconnectemail@gmail.com
    password: bpoj irgx svhc xizh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  secret: DeDuB9695l2RiYlBSZo1MxiA/bRPGcHmMkLfyOFggs8=
  algorithm: AES
  jwt:
    expiration: 86400000 # 1 day
  refresh:
    expiration: 2592000000 # 30 days
  url: http://localhost:8080

recaptcha:
  url: https://www.google.com/recaptcha/api/siteverify
  key:
    secret: 6LfqaLUqAAAAAL6t48rrm0QGp6rPQFtgW6h_iPjw
    site: 6LfqaLUqAAAAAMtZOTid15_GoUNJvHb_o9n6N6Jr

storage:
  root: uploads
  temp: temps
  max-size: 10 # MB

vnpay:
  vnp_Version: 2.1.0
  vnp_CurrCode: VND
  vnp_Locale: vn
  vnp_IpAddr: 127.0.0.1
  vnp_TmnCode: B79SLRRJ
  vnp_HashSecret: 88187SFVCSIYZ0UL2AOMMMDFROEQ2DG7
  vnp_Url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  vnp_apiUrl: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
  vnp_ReturnUrl: http://localhost:8080/vnpay-return

#set up owner account
owner:
  username: owner
  password: owner
  firstname: Chủ
  lastname: cửa hàng
  email: owner@gmail.com
  phone: 0123456789
  gender: true
  birthday: 2004-09-14
  address: 123 Đường 123, Quận 1, TP.HCM
  avatar: images/male.png
